import { Dimensions, StyleSheet } from "react-native";
import { theme } from "@/theme";

const SCREEN_HEIGHT = Dimensions.get('window').height;

export default StyleSheet.create({
    overlay: {
        flex: 1,
        justifyContent: 'flex-end',
    },
    backgroundLink: {
        ...StyleSheet.absoluteFillObject,
    },
    modal: {
        width: '100%',
        maxHeight: SCREEN_HEIGHT * 0.92,
        backgroundColor: '#fff',
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        paddingTop: 16,
        paddingHorizontal: 24,
        elevation: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -5 },
        shadowOpacity: 0.2,
        shadowRadius: 10,
    },
    indicator: {
        width: 40,
        height: 6,
        backgroundColor: '#E5E5E5',
        borderRadius: 3,
        alignSelf: 'center',
        marginBottom: 16,
    },
    title: {
        fontFamily: theme.typography.fontFamily.bold,
        fontSize: 18,
        color: theme.colors.base.gray700,
        marginBottom: 16,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 12,
    },
    sectionIcon: {
        width: 28,
        height: 28,
        borderRadius: 6,
        backgroundColor: theme.colors.base.gray200,
        justifyContent: 'center',
        alignItems: 'center',
    },
    sectionTitle: {
        fontFamily: theme.typography.fontFamily.bold,
        fontSize: 13,
        color: theme.colors.base.gray500,
    },
    inputGroup: {
        gap: 10,
        marginBottom: 8,
    },
    statusGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        marginBottom: 8,
    },
    statusOption: {
        width: '48%',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingVertical: 10,
        paddingHorizontal: 12,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: theme.colors.base.gray300,
        backgroundColor: '#fff',
    },
    statusOptionSelected: {
        borderColor: theme.colors.principal.purpleBase,
        backgroundColor: theme.colors.principal.purpleLight,
    },
    statusRadio: {
        width: 16,
        height: 16,
        borderRadius: 8,
        borderWidth: 2,
        borderColor: theme.colors.base.gray300,
        justifyContent: 'center',
        alignItems: 'center',
    },
    statusRadioSelected: {
        borderColor: theme.colors.principal.purpleBase,
    },
    statusRadioInner: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: theme.colors.principal.purpleBase,
    },
    statusDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
    },
    statusOptionText: {
        fontFamily: theme.typography.fontFamily.regular,
        fontSize: 13,
        color: theme.colors.base.gray600,
    },
    serviceRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: theme.colors.base.gray200,
        gap: 12,
    },
    serviceInfo: {
        flex: 1,
        gap: 2,
    },
    serviceName: {
        fontFamily: theme.typography.fontFamily.bold,
        fontSize: 14,
        color: theme.colors.base.gray700,
    },
    serviceDetail: {
        fontFamily: theme.typography.fontFamily.regular,
        fontSize: 12,
        color: theme.colors.base.gray500,
    },
    addServiceButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        paddingVertical: 14,
        borderWidth: 1,
        borderColor: theme.colors.base.gray300,
        borderRadius: 12,
        borderStyle: 'dashed',
        marginTop: 8,
        marginBottom: 8,
    },
    addServiceText: {
        fontFamily: theme.typography.fontFamily.bold,
        fontSize: 14,
        color: theme.colors.principal.purpleBase,
    },
    investimentoCard: {
        borderWidth: 1,
        borderColor: theme.colors.base.gray300,
        borderRadius: 12,
        padding: 16,
        gap: 10,
        marginBottom: 8,
    },
    investRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    investLabel: {
        fontFamily: theme.typography.fontFamily.regular,
        fontSize: 14,
        color: theme.colors.base.gray600,
    },
    investValue: {
        fontFamily: theme.typography.fontFamily.regular,
        fontSize: 14,
        color: theme.colors.base.gray700,
    },
    descontoInput: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: theme.colors.base.gray200,
        borderRadius: 8,
        paddingHorizontal: 10,
        paddingVertical: 4,
    },
    descontoField: {
        fontFamily: theme.typography.fontFamily.regular,
        fontSize: 14,
        color: theme.colors.base.gray700,
        minWidth: 28,
        textAlign: 'right',
    },
    descontoPercent: {
        fontFamily: theme.typography.fontFamily.regular,
        fontSize: 14,
        color: theme.colors.base.gray600,
        marginLeft: 2,
    },
    investDiscount: {
        fontFamily: theme.typography.fontFamily.regular,
        fontSize: 14,
        color: theme.colors.feedback.dangerBase,
    },
    investTotalRow: {
        borderTopWidth: 1,
        borderTopColor: theme.colors.base.gray200,
        paddingTop: 8,
        marginTop: 2,
    },
    investTotalLabel: {
        fontFamily: theme.typography.fontFamily.bold,
        fontSize: 14,
        color: theme.colors.base.gray700,
    },
    investTotalValues: {
        alignItems: 'flex-end',
        gap: 2,
    },
    investSubtotalStrike: {
        fontFamily: theme.typography.fontFamily.regular,
        fontSize: 12,
        color: theme.colors.base.gray400,
        textDecorationLine: 'line-through',
    },
    investTotalValue: {
        fontFamily: theme.typography.fontFamily.bold,
        fontSize: 16,
        color: theme.colors.base.gray700,
    },
    buttonsRow: {
        flexDirection: 'row',
        gap: 12,
        paddingVertical: 16,
        backgroundColor: '#fff',
    },
    cancelButton: {
        flex: 1,
        paddingVertical: 14,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: theme.colors.base.gray300,
        alignItems: 'center',
    },
    cancelButtonText: {
        fontFamily: theme.typography.fontFamily.bold,
        fontSize: 14,
        color: theme.colors.base.gray600,
    },
    saveButton: {
        flex: 1,
        paddingVertical: 14,
        borderRadius: 12,
        backgroundColor: theme.colors.principal.purpleBase,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
    },
    saveButtonText: {
        fontFamily: theme.typography.fontFamily.bold,
        fontSize: 14,
        color: '#fff',
    },
    subOverlay: {
        flex: 1,
        justifyContent: 'flex-end',
        backgroundColor: 'rgba(0,0,0,0.5)',
    },
    subModal: {
        width: '100%',
        backgroundColor: '#fff',
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        padding: 24,
        paddingBottom: 40,
        gap: 16,
        elevation: 30,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -5 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
    },
    subModalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    subModalTitle: {
        fontFamily: theme.typography.fontFamily.bold,
        fontSize: 18,
        color: theme.colors.base.gray700,
    },
    serviceInput: {
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: theme.colors.base.gray300,
        backgroundColor: theme.colors.base.gray200,
        fontFamily: theme.typography.fontFamily.regular,
        fontSize: 14,
        color: theme.colors.base.gray700,
    },
    serviceTextarea: {
        height: 100,
        textAlignVertical: 'top',
    },
    priceQtyRow: {
        flexDirection: 'row',
        gap: 12,
        alignItems: 'center',
    },
    priceInput: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: theme.colors.base.gray300,
        backgroundColor: theme.colors.base.gray200,
        gap: 4,
    },
    currencyPrefix: {
        fontFamily: theme.typography.fontFamily.regular,
        fontSize: 14,
        color: theme.colors.base.gray500,
    },
    priceField: {
        flex: 1,
        fontFamily: theme.typography.fontFamily.regular,
        fontSize: 14,
        color: theme.colors.base.gray700,
    },
    qtdControl: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        borderWidth: 1,
        borderColor: theme.colors.base.gray300,
        borderRadius: 12,
        paddingHorizontal: 8,
        paddingVertical: 8,
        backgroundColor: theme.colors.base.gray200,
    },
    qtdButton: {
        width: 28,
        height: 28,
        borderRadius: 8,
        backgroundColor: '#fff',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: theme.colors.base.gray300,
    },
    qtdValue: {
        fontFamily: theme.typography.fontFamily.bold,
        fontSize: 16,
        color: theme.colors.base.gray700,
        minWidth: 24,
        textAlign: 'center',
    },
    subModalButtons: {
        flexDirection: 'row',
        gap: 12,
        alignItems: 'center',
    },
    deleteServiceButton: {
        width: 48,
        height: 48,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: theme.colors.feedback.dangerBase,
        justifyContent: 'center',
        alignItems: 'center',
    },
});
