import { StyleSheet } from "react-native";
import { theme } from "@/theme";

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.colors.base.gray200,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingTop: 56,
        paddingBottom: 16,
        paddingHorizontal: 16,
        backgroundColor: '#fff',
        gap: 12,
        borderBottomWidth: 1,
        borderBottomColor: theme.colors.base.gray200,
    },
    headerTitle: {
        flex: 1,
        fontFamily: theme.typography.fontFamily.bold,
        fontSize: theme.typography.sizes.titleMd,
        color: theme.colors.base.gray700,
    },
    statusBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 5,
        gap: 6,
    },
    statusDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
    },
    statusText: {
        fontFamily: theme.typography.fontFamily.bold,
        fontSize: 12,
    },
    scrollView: {
        flex: 1,
    },
    content: {
        padding: 16,
        gap: 12,
        paddingBottom: 24,
    },
    infoCard: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 20,
        gap: 12,
    },
    iconCircle: {
        width: 44,
        height: 44,
        borderRadius: 10,
        backgroundColor: theme.colors.base.gray200,
        justifyContent: 'center',
        alignItems: 'center',
    },
    titulo: {
        fontFamily: theme.typography.fontFamily.bold,
        fontSize: 20,
        color: theme.colors.base.gray700,
        lineHeight: 26,
    },
    label: {
        fontFamily: theme.typography.fontFamily.regular,
        fontSize: 12,
        color: theme.colors.base.gray400,
        marginBottom: 2,
    },
    value: {
        fontFamily: theme.typography.fontFamily.regular,
        fontSize: 14,
        color: theme.colors.base.gray600,
    },
    datesRow: {
        flexDirection: 'row',
        gap: 32,
    },
    servicesCard: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 20,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 16,
    },
    sectionIcon: {
        width: 28,
        height: 28,
        borderRadius: 6,
        justifyContent: 'center',
        alignItems: 'center',
    },
    sectionTitle: {
        fontFamily: theme.typography.fontFamily.bold,
        fontSize: 14,
        color: theme.colors.base.gray500,
    },
    serviceItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        paddingVertical: 12,
        gap: 12,
    },
    serviceItemBorder: {
        borderBottomWidth: 1,
        borderBottomColor: theme.colors.base.gray200,
    },
    serviceInfo: {
        flex: 1,
        gap: 2,
    },
    serviceName: {
        fontFamily: theme.typography.fontFamily.bold,
        fontSize: 14,
        color: theme.colors.base.gray700,
    },
    serviceDescription: {
        fontFamily: theme.typography.fontFamily.regular,
        fontSize: 12,
        color: theme.colors.base.gray500,
        lineHeight: 16,
    },
    serviceValues: {
        alignItems: 'flex-end',
        gap: 2,
    },
    servicePrice: {
        fontFamily: theme.typography.fontFamily.bold,
        fontSize: 14,
        color: theme.colors.base.gray700,
    },
    serviceQty: {
        fontFamily: theme.typography.fontFamily.regular,
        fontSize: 12,
        color: theme.colors.base.gray500,
    },
    totalsCard: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 20,
    },
    totalsIconRow: {
        flexDirection: 'row',
        gap: 12,
        alignItems: 'flex-start',
    },
    totalsRows: {
        flex: 1,
        gap: 8,
    },
    totalRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    discountLabelRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    totalLabel: {
        fontFamily: theme.typography.fontFamily.regular,
        fontSize: 14,
        color: theme.colors.base.gray600,
    },
    totalValue: {
        fontFamily: theme.typography.fontFamily.regular,
        fontSize: 14,
        color: theme.colors.base.gray700,
    },
    discountBadge: {
        backgroundColor: theme.colors.feedback.successLight,
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 4,
    },
    discountBadgeText: {
        fontFamily: theme.typography.fontFamily.bold,
        fontSize: 11,
        color: theme.colors.feedback.successBase,
    },
    discountValue: {
        fontFamily: theme.typography.fontFamily.regular,
        fontSize: 14,
        color: theme.colors.feedback.dangerBase,
    },
    totalFinalDivider: {
        height: 1,
        backgroundColor: theme.colors.base.gray200,
        marginVertical: 4,
    },
    totalFinalLabel: {
        fontFamily: theme.typography.fontFamily.bold,
        fontSize: 14,
        color: theme.colors.base.gray700,
    },
    totalFinalValue: {
        fontFamily: theme.typography.fontFamily.bold,
        fontSize: theme.typography.sizes.titleMd,
        color: theme.colors.base.gray700,
    },
    bottomBar: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingTop: 12,
        paddingBottom: 32,
        backgroundColor: '#fff',
        gap: 10,
        borderTopWidth: 1,
        borderTopColor: theme.colors.base.gray200,
    },
    actionIconButton: {
        width: 44,
        height: 44,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: theme.colors.base.gray300,
        justifyContent: 'center',
        alignItems: 'center',
    },
    shareButton: {
        flex: 1,
        backgroundColor: theme.colors.principal.purpleBase,
        borderRadius: 10,
        height: 44,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
    },
    shareButtonText: {
        color: '#fff',
        fontFamily: theme.typography.fontFamily.bold,
        fontSize: 14,
    },
});
