import { theme } from "@/theme";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.colors.base.gray100,
        padding: 24,
        gap: 16,
    },
    header: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 8,
    },
    circle: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: theme.colors.base.gray200,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: theme.colors.base.gray300,
    },
    filterOverlay: {
        flex: 1,
        justifyContent: 'flex-end',
    },
    filterBackground: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(0,0,0,0.5)',
    },
    filterModal: {
        backgroundColor: '#fff',
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        padding: 24,
        paddingBottom: 40,
        gap: 14,
        elevation: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.2,
        shadowRadius: 10,
    },
    filterIndicator: {
        width: 40,
        height: 6,
        backgroundColor: theme.colors.base.gray300,
        borderRadius: 3,
        alignSelf: 'center',
    },
    filterHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    filterTitle: {
        fontFamily: theme.typography.fontFamily.bold,
        fontSize: 18,
        color: theme.colors.base.gray700,
    },
    filterSectionTitle: {
        fontFamily: theme.typography.fontFamily.bold,
        fontSize: 14,
        color: theme.colors.base.gray500,
    },
    checkboxGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
    },
    checkboxItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        width: '45%',
    },
    checkbox: {
        width: 20,
        height: 20,
        borderRadius: 4,
        borderWidth: 2,
        borderColor: theme.colors.base.gray300,
        justifyContent: 'center',
        alignItems: 'center',
    },
    checkboxChecked: {
        borderColor: theme.colors.principal.purpleBase,
        backgroundColor: theme.colors.principal.purpleBase,
    },
    checkboxInner: {
        width: 10,
        height: 10,
        backgroundColor: '#fff',
        borderRadius: 2,
    },
    checkboxDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
    },
    checkboxLabel: {
        fontFamily: theme.typography.fontFamily.regular,
        fontSize: 14,
        color: theme.colors.base.gray600,
    },
    radioGroup: {
        gap: 12,
    },
    radioItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    radio: {
        width: 20,
        height: 20,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: theme.colors.base.gray300,
        justifyContent: 'center',
        alignItems: 'center',
    },
    radioSelected: {
        borderColor: theme.colors.principal.purpleBase,
    },
    radioInner: {
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: theme.colors.principal.purpleBase,
    },
    radioLabel: {
        fontFamily: theme.typography.fontFamily.regular,
        fontSize: 14,
        color: theme.colors.base.gray600,
    },
    filterButtons: {
        flexDirection: 'row',
        gap: 12,
        marginTop: 4,
    },
    resetButton: {
        flex: 1,
        paddingVertical: 14,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: theme.colors.base.gray300,
        alignItems: 'center',
    },
    resetButtonText: {
        fontFamily: theme.typography.fontFamily.bold,
        fontSize: 14,
        color: theme.colors.base.gray600,
    },
    applyButton: {
        flex: 1,
        paddingVertical: 14,
        borderRadius: 12,
        backgroundColor: theme.colors.principal.purpleBase,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
    },
    applyButtonText: {
        fontFamily: theme.typography.fontFamily.bold,
        fontSize: 14,
        color: '#fff',
    },
});
